# Generated by Django 5.2.1 on 2025-06-13 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggested_prompt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField()),
            ],
            options={
                'db_table': 'sugested_prompt',
            },
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='user',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='content',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='category',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='logo',
            name='system_prompt',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logo',
            name='temprature',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logo',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='backoffice_engine.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logo',
            name='user_prompt',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='credit',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='backoffice_engine.plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=-1, max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=-1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice_engine.user'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice_engine.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
        migrations.AlterModelTable(
            name='logo',
            table='generated_image',
        ),
        migrations.AlterModelTable(
            name='plan',
            table='plan',
        ),
        migrations.AlterModelTable(
            name='subscription',
            table='subscription',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
        migrations.DeleteModel(
            name='suggestion',
        ),
    ]
