# Generated by Django 5.2.1 on 2025-06-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0002_suggested_prompt_remove_suggestion_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
    ]
