# Generated by Django 5.2.1 on 2025-06-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0003_plan_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pending_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='backoffice_engine/user_generated_logo'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='credit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_used',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
