# Generated by Django 5.2.1 on 2025-06-25 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0004_subscription_pending_credit_alter_logo_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logo',
            table='generated_logo',
        ),
    ]
