# Generated by Django 5.2.1 on 2025-06-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0006_alter_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='backoffice_engine/user_generated_logo'),
        ),
    ]
