# Generated by Django 5.2.1 on 2025-06-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0007_alter_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_used',
            field=models.IntegerField(null=True),
        ),
    ]
